core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = 'MYExpenses Adminstração'
admin.site.site_title = 'MYExpenses'
admin.site.index_title = 'Bem-Vindo(a)'

urlpatterns = [
    path('', include('expenses.urls')),
    path('profile/', include('profiles.urls')),
    path('accounts/', include('allauth.urls')),
    path('earns/', include('earns.urls')),
    path('expenses_dashboard/', include('expenses_dashboard.urls')),
    path('earnings_dashboard/', include('earnings_dashboard.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

earnings_dashboard/urls.py
from django.urls import path
from .views import EarningsDashboardView, EarningsReportsListView, earnings_pdf_view

app_name="earning_dash"

urlpatterns = [
    path('earnings_dash/', EarningsDashboardView.as_view(), name="earnings_dash"),
    path('earnings_reports/', EarningsReportsListView.as_view(), name="earnings_reports"),
    path('earnings_pdf/', earnings_pdf_view, name="earnings_pdf"),
]

earns/urls.py
from django.urls import path
from .views import EarnsListView, SearchEarns, EarnsCreateView, EarnsUpdateView, EarnDeleteView


app_name = 'earn'

urlpatterns = [
    path('myearns/', EarnsListView.as_view(), name="list"),
    path('search/', SearchEarns.as_view(), name="search"),
    path('create_earn/', EarnsCreateView.as_view(), name="create"),
    path('<int:pk>/update_earn/', EarnsUpdateView.as_view(), name="update"),
    path('<int:pk>/delete_earn/', EarnDeleteView.as_view(), name="delete"),
]

expenses/urls.py
from django.urls import path
from .views import ExpenseListView, HomeTemplateView, ExpenseCreateView, ExpenseUpdateView, ExpenseDeleteView, SearchExpenses


app_name = 'expense'

urlpatterns = [
    path('', HomeTemplateView.as_view(), name="home"),
    path('expenses/', ExpenseListView.as_view(), name="list"),
    path('create_expense/', ExpenseCreateView.as_view(), name="create"),
    path('<str:pk>/update_expense/', ExpenseUpdateView.as_view(), name="update"),
    path('delete_expense/<str:pk>/', ExpenseDeleteView.as_view(), name="delete"),
    path('search/', SearchExpenses.as_view(), name="search")
]

profiles/urls.py
from django.urls import path
from .views import ProfileView, ProfileUpdateInfoView

app_name = 'profile'

urlpatterns = [
    path('profile/<str:pk>/', ProfileView.as_view(), name='profile'),
    path('update_info/<str:pk>/', ProfileUpdateInfoView.as_view(), name='update_info'),
]

templates/parciais/float_menu.html
{% load static %}
<div class="fixed-action-btn">
    <a href="#" id="float-menu" class="btn-floating btn-large float-btn blue">
        <i class="large material-icons">add</i>
    </a>
    <ul>
        <li>
            <a href="{% url 'profile:profile' user.profile.pk %}" class="btn-floating 
            blue tooltipped" data-position="left" 
            data-tooltip="Perfil">
                <i class="material-icons">person</i>
            </a>
        </li>
        <li>
            <a href="{% url 'expense:create' %}" class="btn-floating 
            float-btn-content tooltipped" data-position="left" 
            data-tooltip="Adicionar novo gasto">
                <i class="material-icons">create</i>
            </a>
        </li>
        <li>
            <a href="{% url 'earn:create' %}" class="btn-floating 
            float-btn-content orange tooltipped" data-position="left" 
            data-tooltip="Adicionar novo ganho">
                <i class="material-icons">create</i>
            </a>
        </li>
        <li>
            <a href="{% url 'earning_dash:earnings_dash'%}" class="btn-floating 
            green tooltipped" data-position="left" 
            data-tooltip="Gráfico de ganhos">
                <i class="material-icons">trending_up</i>
            </a>
        </li>
        <li>
            <a href="{% url 'expense_dash:expenses_dash'%}" class="btn-floating 
            red tooltipped" data-position="left" 
            data-tooltip="Gráfico de gastos">
                <i class="material-icons">trending_down</i>
            </a>
        </li>
    </ul>
</div>

templates/parciais/messages.html
{% load static %}
{% if messages %}
<link rel="stylesheet" href="{% static 'assets/styles/main.css' %}">
    {% for message in messages%}
    <div class="row">
        <div class="col s12 m10 l6 offset-l3 offset-m1">
            <div class="card {{message.tags}} msg">
                <div class="card-content">
                    <a href="#" class="close-msg"><i class="material-icons left">
                        close</i>
                    </a>
                    <p class="text-card white-text center">{{message}}</p>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
{% endif %}    
    <script src="{% static 'assets/js/messages.js' %}"></script>

templates/parciais/pagination.html
{% load static %}
{% load filter_args %}
{% if is_paginated %}
    <ul class="pagination">
        {% if page_obj.has_previous%}
        <li><a href="?{% url_replace 'page' page_obj.previous_page_number request.GET.urlencode %}"><i class="material-icons indigo-text">
            chevron_left</i></a>
        </li>
        {% else %}
        <li><a href="#" class="disabled"></a><i class="material-icons indigo-text">
            chevron_left</i></a>
        </li>
        {% endif %}
        {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
        <li class="active blue darken-4"><a href="?{% url_replace 'page' num request.GET.urlencode %}" 
            class="white-text">{{num}}</a>
        </li>
        {% else %}
        <li class="waves-effect"><a href="?{% url_replace 'page' num request.GET.urlencode %}" 
            class="indigo-text">{{num}}</a>
        </li>
        {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
        <li class="waves-effect"><a href="?{% url_replace 'page' page_obj.next_page_number request.GET.urlencode %}" 
            class="indigo-text"><i class="material-icons">chevron_right</i></a>
        </li>
        {% else %}
        <li class="disabled"><a href="#!"></a><i class="material-icons indigo-text">
            chevron_right</i></a>
        </li>
        {% endif %}
    </ul>
{% endif %}