core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = 'MYExpenses Adminstração'
admin.site.site_title = 'MYExpenses'
admin.site.index_title = 'Bem-Vindo(a)'

urlpatterns = [
    path('', include('expenses.urls')),
    path('profile/', include('profiles.urls')),
    path('accounts/', include('allauth.urls')),
    path('earns/', include('earns.urls')),
    path('expenses_dashboard/', include('expenses_dashboard.urls')),
    path('earnings_dashboard/', include('earnings_dashboard.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

earns/urls.py
from django.urls import path
from .views import EarnsListView, SearchEarns, EarnsCreateView, EarnsUpdateView, EarnDeleteView


app_name = 'earn'

urlpatterns = [
    path('myearns/', EarnsListView.as_view(), name="list"),
    path('search/', SearchEarns.as_view(), name="search"),
    path('create_earn/', EarnsCreateView.as_view(), name="create"),
    path('<int:pk>/update_earn/', EarnsUpdateView.as_view(), name="update"),
    path('<int:pk>/delete_earn/', EarnDeleteView.as_view(), name="delete"),
]

expenses/urls.py
from django.urls import path
from .views import ExpenseListView, HomeTemplateView, ExpenseCreateView, ExpenseUpdateView, ExpenseDeleteView, SearchExpenses


app_name = 'expense'

urlpatterns = [
    path('', HomeTemplateView.as_view(), name="home"),
    path('expenses/', ExpenseListView.as_view(), name="list"),
    path('create_expense/', ExpenseCreateView.as_view(), name="create"),
    path('<str:pk>/update_expense/', ExpenseUpdateView.as_view(), name="update"),
    path('delete_expense/<str:pk>/', ExpenseDeleteView.as_view(), name="delete"),
    path('search/', SearchExpenses.as_view(), name="search")
]

expenses/models.py
from django.db import models
from profiles.models import Profile
from django.conf import settings


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name="Nome da categoria", unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'
           

class Currencies(models.Model):
    currency = models.CharField(max_length=20, default=None, verbose_name="Moeda")

    def __str__(self):
        return self.currency

        class Meta:
            verbose_name = 'Moeda'
            verbose_name_plural = 'Moedas'                           


class Expenses(models.Model):
    currency = models.ForeignKey(Currencies, on_delete=models.CASCADE, verbose_name="Moeda")
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, 
    related_name="exp", default=None)
    category = models.ForeignKey(Category, on_delete=models.PROTECT, 
    verbose_name="Categoria")
    title = models.CharField(max_length=200, verbose_name="Título")
    description = models.CharField(max_length=800, verbose_name="Descrição")
    quantity = models.DecimalField(max_digits=19, decimal_places=2, 
    verbose_name="Valor")
    date = models.DateField(verbose_name="Data")
    long_term = models.BooleanField(default=False, verbose_name="Gasto fixo")

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-long_term']
        verbose_name = 'Gasto'
        verbose_name_plural = 'Gastos'




                

expenses/forms.py
from django.forms import ModelForm, DateInput
from .models import Expenses
from django.forms import ValidationError


class ExpenseCreationForm(ModelForm):
    class Meta:
        model = Expenses
        fields = ['category', 'description', 'date', 'title', 'quantity', 'currency', 'long_term']
        widgets = {
            'date': DateInput(attrs={'type': 'text', 'class': 'datepicker'})
        }


class ExpenseUpdateForm(ModelForm):        
    class Meta:
        model = Expenses
        fields = ['category', 'description', 'date', 'title', 'quantity', 'currency', 'long_term']
        widgets = {
            'date': DateInput(attrs={'type': 'text', 'class': 'datepicker'})
        }

expenses/views.py
from django.shortcuts import render
from .models import Category, Expenses, Currencies
from profiles.models import Profile
from django.views.generic.base import TemplateView
from django.views.generic import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.contrib import messages
from django.db.models import Q
from django.conf import settings
from django.urls import reverse, reverse_lazy
from .forms import ExpenseCreationForm, ExpenseUpdateForm
from django_filters.views import FilterView
from django.contrib.auth.mixins import LoginRequiredMixin
from .filters import ExpenseFilter
import os
import json


class HomeTemplateView(TemplateView):
    template_name = 'expenses/landing_page.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
    
        validate_create_currency = Currencies.objects.all().exists()
        if validate_create_currency == False:
            with open(os.path.join(settings.BASE_DIR, 'currency.json'), 'r', 
            encoding="utf8") as data:
                data_json = json.loads(data.read())
                for v in data_json.values():
                    symbol = v["symbol"]
                    create_currency = Currencies.objects.create(currency=symbol)
        get_currency = Currencies.objects.all()
        context["currencies"] = get_currency
        return context 


class ExpenseListView(LoginRequiredMixin, FilterView):
    model = Expenses
    template_name = 'expenses/expenses.html'
    paginate_by = 6
    context_object_name = 'expenses'
    login_url = 'account_login'
    filterset_class = ExpenseFilter

    def get_queryset(self):
        profile = Profile.objects.filter(user=self.request.user)
        return Expenses.objects.filter(author__in=profile)
    

class SearchExpenses(ExpenseListView):
    def get_queryset(self, *args, **kwargs):
        q = self.request.GET.get('q') or self.request.session['q'] 
        qs = super().get_queryset(*args, **kwargs)

        if not q:
            return qs

        self.request.session['q'] = q

        qs = qs.filter(
            Q(title__icontains=q)|
            Q(description__icontains=q)|
            Q(quantity__icontains=q)|
            Q(date__icontains=q)
        )
        
        self.request.session.save()

        return qs   


class ExpenseCreateView(LoginRequiredMixin, CreateView):
    model = Expenses
    template_name = 'expenses/add_expense.html'
    form_class = ExpenseCreationForm
    login_url = 'account_login'
    
    def form_valid(self, form):
        profile = Profile.objects.get(user=self.request.user)
        title_input = form.cleaned_data.get('title')
        title_exists = Expenses.objects.filter(author=profile, title=title_input).count()
        if title_exists == 0:
            instance = form.save(commit=False)
            instance.author = profile
            instance.currency = form.cleaned_data.get('currency')
            instance.category = form.cleaned_data.get('category')
            instance.save()           
            messages.success(self.request, f'{title_input} foi criado com sucesso!')
            return super(ExpenseCreateView, self).form_valid(form)
        else:
            messages.error(self.request, 'Este título já existe!')
            return self.form_invalid(form)    

    def form_invalid(self, form):
        self.form_class    
        return super(ExpenseCreateView, self).form_invalid(form)    
    
    def get_success_url(self):
        return reverse('expense:create')
    

class ExpenseUpdateView(LoginRequiredMixin, UpdateView):
    model = Expenses
    template_name = 'expenses/update_expense.html'
    form_class = ExpenseUpdateForm
    login_url = 'account_login'

    def form_valid(self, form):
        title_input = form.cleaned_data.get('title')
        instance = form.save(commit=False)
        instance.author = Profile.objects.get(user=self.request.user)
        instance.currency = form.cleaned_data.get('currency')
        instance.category = form.cleaned_data.get('category')
        instance.save()
        messages.success(self.request, f'{title_input} foi atualizado com sucesso!')
        return super(ExpenseUpdateView, self).form_valid(form)

    def form_invalid(self, form):
        self.form_class    
        return super(ExpenseUpdateView, self).form_invalid(form)    

    def get_success_url(self):
        return reverse('expense:list')


class ExpenseDeleteView(LoginRequiredMixin, DeleteView):
    model = Expenses    
    template_name = 'expenses/delete_expense.html'
    login_url = 'account_login'

    def get_queryset(self):
        profile = Profile.objects.get(user=self.request.user)
        queryset = Expenses.objects.filter(author=profile, pk=self.kwargs['pk'])
        return queryset
    
    def get_success_url(self):
        messages.success(self.request, f'"{self.object.title}" foi excluído com sucesso!')
        return reverse('expense:list')    

expenses/templates/expenses/add_expense.html
{% extends 'base.html' %}     
{% load static %}

{% block title %} Adicionar Gasto{% endblock %}
{% block content %} 
    <main class="main-add-exp" style="background-image: url('{% static 'assets/img/bg-add.jpg' %}')">
        <section>
            <div class="container card-container">
                {% include 'parciais/messages.html'%}
                <div class="row">
                    <div class="col s12 m10 l6 offset-m1 offset-l3">
                        <nav class="transparent">
                            <div class="nav-wrapper">
                              <div class="col s12">
                                <a href="{% url 'expense:list' %}" class="breadcrumb">Meus Gastos</a>
                                <a href="{% url 'expense:create'%}" class="breadcrumb">Adicionar Gastos</a>
                              </div>
                            </div>
                        </nav>
                        <div class="card card-exp">
                            <div class="card-content">
                                <h1 class="title-card center">
                                    ADICIONAR GASTO
                                </h1>
                                <div class="row">
                                    
                                    <form action="" class="add-exp-form" 
                                    method="POST">
                                        {% csrf_token %}
                                        <div class="row">
                                            <div class="input-field col s12 m6 l6">
                                                <i class="material-icons prefix update-icon">create</i>
                                                {{form.title}}
                                                <label for="title">Título</label>
                                                <span class="helper-text red-text" 
                                                data-error="wrong" data-success="right">
                                                    {{form.title.errors}}
                                                </span>
                                            </div>
                                            <div class="input-field col s12 m6 l6">
                                                <i class="material-icons prefix update-icon">
                                                    format_list_bulleted
                                                </i>
                                                <select id="id_category" name="category">
                                                    {% for category in form.category %}
                                                    {{category}}
                                                    {% endfor %}   
                                                </select>
                                                <label>Categoria</label>
                                                <span class="helper-text red-text" 
                                                data-error="wrong" data-success="right">
                                                    {{form.category.errors}}
                                                </span>
                                            </div>
                                        </div> 
                                        <div class="row">
                                            <div class="input-field col s12 m6 l6">
                                                <i class="material-icons prefix update-icon">
                                                    attach_money
                                                </i>
                                                {{form.quantity}}
                                                <label for="title">Valor</label>
                                                <span class="helper-text red-text" 
                                                data-error="wrong" data-success="right">
                                                    {{form.quantity.errors}}
                                                </span>
                                            </div>
                                            <div class="input-field col s12 m6 l6">
                                                <i class="material-icons prefix update-icon">
                                                    monetization_on
                                                </i>
                                                <select id="id_currency" name="currency">
                                                    {% for c in form.currency %}
                                                    {{c}}
                                                    {% endfor %}  
                                                </select>
                                                <label>Moeda</label>
                                                <span class="helper-text red-text" 
                                                data-error="wrong" data-success="right">
                                                    {{form.currency.errors}}
                                                </span>
                                            </div>
                                        </div> 
                                        <div class="row">
                                            <div class="input-field col s12 l12 m12">
                                                <i class="material-icons prefix update-icon">
                                                    description
                                                </i>
                                                {{form.description}}
                                                <label for="description">Descrição</label>
                                                <span class="helper-text red-text" 
                                                data-error="wrong" data-success="right">
                                                    {{form.description.errors}}
                                                </span>
                                            </div>
                                        </div> 
                                        <div class="row">
                                            <div class="input-field col s12 l12 m12">
                                                <i class="material-icons prefix 
                                                    update-icon">date_range
                                                </i>
                                                {{form.date}}
                                                <label for="date">Data</label>
                                                <span class="helper-text red-text" 
                                                data-error="wrong" data-success="right">
                                                    {{form.date.errors}}
                                                </span>
                                            </div>
                                        </div>  
                                        <label class="col s2 l3 m3 check-label">
                                            {{form.long_term}}
                                            <span>Gasto Mensal</span>
                                        </label> 
                                        <span class="helper-text red-text" 
                                            data-error="wrong" data-success="right">
                                            {{form.long_term.errors}}
                                        </span>
                                        <button type="submit" class="btn btn-add">Adicionar</button>                    
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% include 'parciais/float_menu.html' %}
            </div>
        </section>                  
    </main>
{% endblock %}
    

expenses/templates/expenses/expenses.html
{% extends 'base.html' %}     
{% load static %}

{% block title %}Meus Gastos{% endblock %}
{% block content %}     
    <main class="main-content">
        <section class="center">
            <div class="container card-container">
                <div class="row">
                    <div class="col s12 m10 l10 offset-l1 offset-m1">
                        <div class="card card-filter">
                            <div class="card-body">
                                <p class="text-card title-filter">
                                    <i class="material-icons">
                                        filter_list
                                    </i>
                                    Filtrar por
                                </p>
                                <div class="row">
                                    <div class="col l12 m12 s12">
                                        <form action="" method="GET" class="filter-form">
                                            <div class="input-field col s12 m6 l3">
                                                {{filter.form.category}}
                                                <label>Categoria</label>
                                            </div>  
                                            <div class="input-field col s12 m6 l3">
                                                {{filter.form.currency}}
                                                <label>Moeda</label>
                                            </div> 
                                            <div class="input-field col s12 m6 l3">
                                                {{filter.form.long_term}}
                                                <label>Mensal</label>
                                            </div>  
                                            <div class="input-field col s12 m6 l3">
                                                {{filter.form.start_date}}
                                                <label>Data (Intervalo inicial)</label>
                                            </div>
                                            <div class="input-field col s12 m6 l3">
                                                {{filter.form.end_date}}
                                                <label>Data (Intervalo final)</label>
                                            </div>
                                            <button type="submit" class="btn btn-filter">
                                                Filtrar
                                            </button>
                                        </form>
                                    </div>    
                                </div>
                            </div>        
                        </div>        
                    </div>
                </div>
            </div>
        </section>
        <section class="center scrollspy" id="search">
            <div class="container">
                <div class="container search-container">
                    <h1 class="title center">Meus gastos</h1>
                    <div class="row">
                        <div class="col l12 s10 m12">
                            <form action="{% url 'expense:search' %}" method="GET">
                                <div class="input-field search">
                                    <input class="white search-input" type="text" 
                                    name="q" value="{{request.GET.q}}" id="input-search" 
                                    placeholder="Buscar...">
                                    <label class="label-icon" for="search">
                                        <i class="material-icons right black-text">
                                            search
                                        </i>
                                    </label>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="row center expenses-box">
                    {% include 'parciais/messages.html'%}
                    {% if expenses %}
                    {% for expense in object_list %}
                    <div class="col l4 m6 s12">
                        <div class="card card-expense">
                            <div class="card-content">
                                <a href="{% url 'expense:delete' expense.pk %}">
                                    <i class="material-icons left">
                                        close
                                    </i>
                                </a>
                                <p class="title-card activator">
                                    {{expense.title}}<i class="material-icons right">
                                    more_vert</i>
                                </p>
                                <p class="text-card">{{expense.currency}} {{expense.quantity}}</p>
                            </div>
                            <div class="card-reveal">
                                <span class="card-title title-card">
                                    <a href="{% url 'expense:update' expense.pk %}">
                                        <i class="material-icons left">
                                        mode_edit
                                        </i>
                                    </a>
                                    {{expense.category}}<i class="material-icons right">
                                    close</i>
                                </span>
                                <p class="text-card">
                                    {{expense.description}}
                                </p>
                            </div>
                            <div class="card-action">
                                {% if not expense.long_term %}
                                <p class="text-card">
                                    {{expense.date | date:"d/m/Y"}}
                                </p>
                                {% else %}
                                <p class="text-card">
                                    Dia {{expense.date | date:"d"}}
                                    <a href="#" class="tooltipped" 
                                        data-position="bottom" data-tooltip="Gasto mensal">
                                        <i class="material-icons green-text">
                                            date_range
                                        </i>
                                    </a>
                                </p>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% include 'parciais/pagination.html'%}
                {% endif %}
                {% include 'parciais/float_menu.html' %}
                </div>
        </section>    
    </main>
{% endblock %}

expenses/templates/expenses/landing_page.html
{% extends 'base.html' %}     
{% load static %}

{% block title %}MYExpenses | Gerencie seus Ganhos e Gastos{% endblock %}
    
{% block content %}
    <main class="main-landing-page">
        <section>
            <div class="slider">
                <ul class="slides">
                    <li>
                        <img src="{% static 'assets/img/exp.png' %}">
                        <div class="caption center-align">
                            <h3 class="title-slides">Gerencie seus gastos</h3>
                            {% if not request.user.is_authenticated %}
                            <a href="{% url 'account_signup'%}" class="btn-large btn-register">Cadastre-se</a>
                            {% else %}
                            <a href="{% url 'expense:list'%}" class="btn-large btn-register">Veja seus Gastos</a>
                            {% endif %}
                        </div>
                    </li>
                    <li>
                        <img src="{% static 'assets/img/dash_earn.png' %}">
                        <div class="caption center-align">
                            <h3 class="title-slides">Visualize seu progresso</h3>
                            {% if not request.user.is_authenticated %}
                            <a href="{% url 'account_login'%}" class="btn-large btn-login">Faça Login</a>
                            {% else %}
                            <a href="{% url 'earn:list'%}" class="btn-large btn-login">Veja seu Progresso</a>
                            {% endif %}
                        </div>
                    </li>
                </ul>
            </div>  
        </section>
        <section class="section section-info">
            <div class="row">
                <div class="col s12 m4 l4">
                    <h3 class="section-info-text center">
                        <i class="medium material-icons center">local_atm</i>
                        Com dificuldade para gerenciar sua 
                        vida finaceira?
                    </h3>
                </div>
                <div class="col s12 m4 l4">
                    <h3 class="section-info-text center">
                        <i class="medium material-icons center">create</i>  
                        Cansou de usar papel e caneta?  
                    </h3>
                </div>
                <div class="col s12 m4 l4">
                    <h3 class="section-info-text center">
                        <i class="medium material-icons center">trending_up</i>
                        Quer acompanhar seu progresso para uma vida financeira
                        mais estável?        
                    </h3>
                </div>
            </div>
        </section>
        <section class="section">
            <div class="container card-container">
                <div class="row">
                    <div class="col s12 m4 l4">
                        <div class="card card-resources animate__animated 
                        animate__bounceInLeft animate__delay-2s">
                            <div class="card-content">
                                <h4 class="title-card center">
                                    <i class="small material-icons center">
                                        show_chart
                                    </i>
                                    Visualize seus dados com  
                                    gráficos interativos        
                                </h4>
                            </div>
                        </div>
                    </div>
                    <div class="col s12 m4 l4">
                        <div class="card card-resources  animate__animated 
                        animate__bounceInLeft animate__delay-3s">
                            <div class="card-content">
                                <h4 class="title-card center">
                                    <i class="small material-icons center">
                                        insert_chart
                                    </i>
                                    Gere relatórios para ganhos e gastos                
                                </h4>
                            </div>
                        </div>
                    </div>
                    <div class="col s12 m4 l4">
                        <div class="card card-resources  animate__animated 
                        animate__bounceInLeft animate__delay-4s">
                            <div class="card-content">
                                <h4 class="title-card center">
                                    <i class="small material-icons center">
                                        format_list_bulleted
                                    </i>
                                    Receba lembretes dos seus gastos mensais
                                </h4>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <section class="section section-info">
            <h3 class="section-info-text center">
                Precisa usar o MYExpenses por longas horas?
            </h3>
            <h4 class="section-info-text center">
                Ative o modo escuro no perfil!
            </h4>
        </section>
        <section class="section">
            <div class="row">
                <div class="col s12 m6 l6 animate__animated 
                animate__bounceInLeft animate__delay-4s">
                    <div class="parallax-container parallax-landing-page">
                        <div class="parallax">
                            <img src="{% static 'assets/img/exp.png' %}">
                        </div>
                    </div>
                </div>
                <div class="col s12 m6 l6">
                    <div class="parallax-container parallax-landing-page
                    animate__animated animate__bounceInRight animate__delay-4s">
                        <div class="parallax">
                            <img src="{% static 'assets/img/exp_dark.png' %}">
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
{% endblock %}    