core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = 'MYExpenses Adminstração'
admin.site.site_title = 'MYExpenses'
admin.site.index_title = 'Bem-Vindo(a)'

urlpatterns = [
    path('', include('expenses.urls')),
    path('profile/', include('profiles.urls')),
    path('accounts/', include('allauth.urls')),
    path('earns/', include('earns.urls')),
    path('expenses_dashboard/', include('expenses_dashboard.urls')),
    path('earnings_dashboard/', include('earnings_dashboard.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

earnings_dashboard/urls.py
from django.urls import path
from .views import EarningsDashboardView, EarningsReportsListView, earnings_pdf_view

app_name="earning_dash"

urlpatterns = [
    path('earnings_dash/', EarningsDashboardView.as_view(), name="earnings_dash"),
    path('earnings_reports/', EarningsReportsListView.as_view(), name="earnings_reports"),
    path('earnings_pdf/', earnings_pdf_view, name="earnings_pdf"),
]

earns/urls.py
from django.urls import path
from .views import EarnsListView, SearchEarns, EarnsCreateView, EarnsUpdateView, EarnDeleteView


app_name = 'earn'

urlpatterns = [
    path('myearns/', EarnsListView.as_view(), name="list"),
    path('search/', SearchEarns.as_view(), name="search"),
    path('create_earn/', EarnsCreateView.as_view(), name="create"),
    path('<int:pk>/update_earn/', EarnsUpdateView.as_view(), name="update"),
    path('<int:pk>/delete_earn/', EarnDeleteView.as_view(), name="delete"),
]

expenses/urls.py
from django.urls import path
from .views import ExpenseListView, HomeTemplateView, ExpenseCreateView, ExpenseUpdateView, ExpenseDeleteView, SearchExpenses


app_name = 'expense'

urlpatterns = [
    path('', HomeTemplateView.as_view(), name="home"),
    path('expenses/', ExpenseListView.as_view(), name="list"),
    path('create_expense/', ExpenseCreateView.as_view(), name="create"),
    path('<str:pk>/update_expense/', ExpenseUpdateView.as_view(), name="update"),
    path('delete_expense/<str:pk>/', ExpenseDeleteView.as_view(), name="delete"),
    path('search/', SearchExpenses.as_view(), name="search")
]

profiles/urls.py
from django.urls import path
from .views import ProfileView, ProfileUpdateInfoView

app_name = 'profile'

urlpatterns = [
    path('profile/<str:pk>/', ProfileView.as_view(), name='profile'),
    path('update_info/<str:pk>/', ProfileUpdateInfoView.as_view(), name='update_info'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/img/logo_size.png' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css">
    <script src="https://kit.fontawesome.com/c7b7793bae.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" id="default-style" href="{% static 'assets/styles/main.css' %}">
    <link rel="stylesheet" id="dark-style" href="">
</head>
<body>
    <header class="header-nav">
        <div class="navbar-fixed">
            <nav class="navbar">
                <div class="container nav-container">
                    <div class="nav-wrapper">
                        <a href="{% url 'expense:list' %}" class="brand-logo logo white-text center">MYExpenses</a>
                        <a href="#" data-target="mobile-demo" 
                        class="sidenav-trigger show-on-large"><i class="material-icons">menu</i></a>
                        <ul class="right hide-on-med-and-down up-menu">
                            {% if not request.user.is_authenticated%}
                            <li><a href="{% url 'account_signup' %}"><i class="material-icons left">
                                people_outline</i>Registre-se</a>
                            </li>
                            <li>
                                <a href="{% url 'account_login' %}"><i class="material-icons left white-text">person_add</i>Login</a>
                            </li>
                            {% else %}
                            <li>
                                <a href="{% url 'account_logout' %}"><i class="material-icons left white-text">directions_walk</i>Sair</a>
                            </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
        
        <ul class="sidenav collapsible" id="mobile-demo">
            {% if request.user.is_authenticated %}
            <li>
                <div class="user-view">
                    <div class="background center bg-img-sidenav">
                        <img src="{% static 'assets/img/bg-sidenav.jpg' %}">
                    </div>
                    <a href="{% url 'profile:profile' user.profile.pk %}"><img class="circle" src="{{user.profile.image.url}}"></a>
                    <a href="{% url 'profile:profile' user.profile.pk %}"><span class="white-text name">{{user.username}}</span></a>
                    <a href="{% url 'profile:profile' user.profile.pk %}"><span class="white-text name">{{user.email}}</span></a>
                    <br>
                </div>    
            </li>
            {% endif %}
            <h2 class="sidenav-logo center">MYExpenses</h2>
            {% if request.user.is_authenticated %}
            <div class="divider"></div>
            <li>
                <div class="collapsible-header">
                    <p class="collapse-title">
                        <i class="material-icons left">
                            keyboard_arrow_down
                        </i>
                        Gerenciar
                    </p>
                </div>
                <div class="collapsible-body center">
                    <a href="{% url 'earn:list' %}"><i class="material-icons center sidenav-icon">monetization_on</i>
                        Meus ganhos</a>
                </div>
                <div class="collapsible-body center">
                    <a href="{% url 'expense:list' %}"><i class="material-icons center sidenav-icon">money_off</i>
                        Meus gastos</a>
                </div>
            </li>
            <li>
                <div class="divider"></div>
                <div class="collapsible-header">
                    <p class="collapse-title">
                        <i class="material-icons left">
                            keyboard_arrow_down
                        </i>
                        Gráficos
                    </p>
                </div>
                <div class="collapsible-body center">
                    <a href="{% url 'earning_dash:earnings_dash'%}"><i class="material-icons center sidenav-icon">trending_up</i>
                        Ganhos</a>
                    
                </div>
                <div class="collapsible-body center">
                    <a href="{% url 'expense_dash:expenses_dash'%}"><i class="material-icons center sidenav-icon">trending_down</i>
                        Gastos</a>
                </div>
            </li>
            <li>
                <div class="divider"></div>
                <div class="collapsible-header">
                    <p class="collapse-title">
                        <i class="material-icons left">
                            keyboard_arrow_down
                        </i>
                        Relatórios
                    </p>
                </div>
                <div class="collapsible-body center">
                    <a href="{% url 'earning_dash:earnings_reports'%}"><i class="material-icons center sidenav-icon">insert_chart</i>
                        Ganhos
                    </a>
                </div>
                <div class="collapsible-body center">
                    <a href="{% url 'expense_dash:expenses_reports'%}"><i class="material-icons center sidenav-icon">pie_chart</i>
                        Gastos
                    </a>
                </div>
            </li>
            {% endif %}
            <li>
                <div class="divider"></div>
                <div class="collapsible-header">
                    <p class="collapse-title">
                        <i class="material-icons left">
                            keyboard_arrow_down
                        </i>Usuário
                    </p>
                </div>
                {% if not request.user.is_authenticated %}
                <div class="collapsible-body center">
                    <a href="{% url 'account_login' %}"><i class="material-icons center sidenav-icon">
                        person_add </i> Login</a>     
                </div>
                <div class="collapsible-body center">
                    <a href="{% url 'account_signup' %}"><i class="material-icons center sidenav-icon">
                        people </i> Criar conta</a>        
                </div>
                {% else %}
                <div class="collapsible-body center">
                    <a href="{% url 'profile:profile' user.profile.pk %}"><i class="material-icons center sidenav-icon">
                        person </i> Perfil</a>     
                </div>
                <div class="collapsible-body center">
                    <a href="{% url 'account_logout' %}"><i class="material-icons center sidenav-icon">
                        directions_walk </i> Sair</a>    
                </div>
                {% endif %}
            </li>
        </ul>   
    </header>  

    {% block content %}
        
    {% endblock %}

    <footer class="page-footer main-footer">
        <div class="container">
            <div class="row">
                <div class="col l12 s12 m12">
                    <h5 class="footer-title center logo">MYExpenses</h5>
                    <p class="footer-text center">
                        Gerencie de maneira eficiente seus ganhos e gastos
                    </p>
                </div>
            </div>
        </div>
        <div class="footer-copyright">
            <div class="container">
                <a href="#" class="footer-text">Copyright &copy; 2020 - MYExpenses</a>
            </div>
        </div>
    </footer>

    <script>
        const static = "{% static 'assets/styles' %}"
        const staticDarkThemePath = "{% static 'assets/styles/dark' %}" 
    </script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="{% static 'assets/js/darkmode.js' %}"></script> 
    <script src="{% static 'assets/js/main.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.js"></script>

    {% block scripts %}

    {% endblock scripts %}
</body>
</html>