core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = 'MYExpenses Adminstração'
admin.site.site_title = 'MYExpenses'
admin.site.index_title = 'Bem-Vindo(a)'

urlpatterns = [
    path('', include('expenses.urls')),
    path('profile/', include('profiles.urls')),
    path('accounts/', include('allauth.urls')),
    path('earns/', include('earns.urls')),
    path('expenses_dashboard/', include('expenses_dashboard.urls')),
    path('earnings_dashboard/', include('earnings_dashboard.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

earns/urls.py
from django.urls import path
from .views import EarnsListView, SearchEarns, EarnsCreateView, EarnsUpdateView, EarnDeleteView


app_name = 'earn'

urlpatterns = [
    path('myearns/', EarnsListView.as_view(), name="list"),
    path('search/', SearchEarns.as_view(), name="search"),
    path('create_earn/', EarnsCreateView.as_view(), name="create"),
    path('<int:pk>/update_earn/', EarnsUpdateView.as_view(), name="update"),
    path('<int:pk>/delete_earn/', EarnDeleteView.as_view(), name="delete"),
]

earns/models.py
from django.db import models
from profiles.models import Profile
from expenses.models import Currencies


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name="Nome da categoria", unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'


class Earns(models.Model):
    currency = models.ForeignKey(Currencies, on_delete=models.CASCADE)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.PROTECT, verbose_name="Categoria")
    title = models.CharField(max_length=200, verbose_name="Título")
    description = models.CharField(max_length=800, verbose_name="Descrição")
    quantity = models.DecimalField(max_digits=19, decimal_places=2, verbose_name="Valor")
    date = models.DateField(verbose_name="Data")
    long_term = models.BooleanField(default=False, verbose_name="Ganho fixo")

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-long_term'] 
        verbose_name = 'Ganho'
        verbose_name_plural = 'Ganhos'   

earns/forms.py
from django.forms import ModelForm, DateInput
from .models import Earns
from profiles.models import Profile
from django.contrib.auth.models import User
from django.forms import ValidationError

class EarnsCreationForm(ModelForm):    
    class Meta:
        model = Earns
        fields = ['title', 'category', 'description', 'date', 'quantity', 'currency', 'long_term']
        widgets = {
            'date': DateInput(attrs={'type': 'text', 'class': 'datepicker'})
        }


class EarnsUpdateForm(ModelForm):
    class Meta:
        model = Earns
        fields = ['category', 'title', 'description', 'date', 'quantity', 'currency', 'long_term']
        widgets = {
            'date': DateInput(attrs={'type': 'text', 'class': 'datepicker'})
        }

earns/views.py
from django.shortcuts import render
from .models import Category, Earns
from profiles.models import Profile
from django.db.models import Q
from django.views.generic import CreateView, UpdateView, DeleteView
from django.urls import reverse
from django.contrib import messages
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import EarnsCreationForm, EarnsUpdateForm
from .filters import EarningFilter
from django_filters.views import FilterView


class EarnsListView(LoginRequiredMixin, FilterView):
    model = Earns
    template_name = 'earns/earnings.html'
    context_object_name = 'earns'
    paginate_by = 6
    login_url = 'account_login'
    filterset_class = EarningFilter

    def get_queryset(self):
        profile = Profile.objects.filter(user=self.request.user)
        return Earns.objects.filter(author__in=profile)


class SearchEarns(EarnsListView):
    def get_queryset(self, *args, **kwargs):
        q = self.request.GET.get('q') or self.request.session['q'] 
        qs = super().get_queryset(*args, **kwargs)

        if not q:
            return qs

        self.request.session['q'] = q

        qs = qs.filter(
            Q(title__icontains=q)|
            Q(description__icontains=q)|
            Q(quantity__icontains=q)|
            Q(date__icontains=q)
        )
        
        self.request.session.save()

        return qs   


class EarnsCreateView(LoginRequiredMixin, CreateView):
    model = Earns
    template_name = 'earns/add_earning.html'
    form_class = EarnsCreationForm
    login_url = 'account_login'
    
    def form_valid(self, form):
        profile = Profile.objects.get(user=self.request.user)
        title_input = form.cleaned_data.get('title')
        title_exists = Earns.objects.filter(author=profile, title=title_input).count()
        if title_exists == 0:
            instance = form.save(commit=False)
            instance.author = profile
            instance.currency = form.cleaned_data.get('currency')
            instance.category = form.cleaned_data.get('category')
            instance.save()
            messages.success(self.request, f'{title_input} foi criado com sucesso!')
            return super(EarnsCreateView, self).form_valid(form)
        else:
            messages.error(self.request, 'Este título já existe!')
            return self.form_invalid(form)
    
    def get_success_url(self):
        return reverse('earn:create')


class EarnsUpdateView(LoginRequiredMixin, UpdateView):
    model = Earns
    template_name = 'earns/update_earning.html'
    form_class = EarnsUpdateForm
    login_url = 'account_login'

    def form_valid(self, form):
        title_input = form.cleaned_data.get('title')
        instance = form.save(commit=False)
        instance.author = Profile.objects.get(user=self.request.user)
        instance.currency = form.cleaned_data.get('currency')
        instance.category = form.cleaned_data.get('category')
        instance.save()
        messages.success(self.request, f'{title_input} foi atualizado com sucesso!')
        return super(EarnsUpdateView, self).form_valid(form)

    def form_invalid(self, form):
        self.form_class    
        return super(EarnsUpdateView, self).form_invalid(form)    

    def get_success_url(self):
        return reverse('earn:list')


class EarnDeleteView(LoginRequiredMixin, DeleteView):
    model = Earns
    template_name = 'earns/delete_earn.html'
    login_url = 'account_login'

    def get_queryset(self):
        profile = Profile.objects.get(user=self.request.user)    
        queryset = Earns.objects.filter(author=profile, pk=self.kwargs['pk'])
        return queryset
    
    def get_success_url(self):
        messages.success(self.request, f'"{self.object.title}" foi excluído com sucesso!')
        return reverse('earn:list')

earns/templates/earns/add_earning.html
{% extends 'base.html' %}      
{% load static %}

{% block title %}Adicionar Ganhos{% endblock %}

{% block content %}    
    <main class="main-add-earn" style="background-image: url('{% static 'assets/img/bg-add.jpg' %}')">
        <section>
            <div class="container card-container">
                {% include 'parciais/messages.html' %}
                <div class="row">
                    <div class="col s12 m10 l6 offset-m1 offset-l3">
                        <nav class="transparent">
                            <div class="nav-wrapper">
                              <div class="col s12">
                                <a href="{% url 'earn:list' %}" class="breadcrumb">
                                    Meus Ganhos
                                </a>
                                <a href="{% url 'earn:create'%}" class="breadcrumb">
                                    Adicionar Ganhos
                                </a>
                              </div>
                            </div>
                        </nav>
                        <div class="card card-exp">
                            <div class="card-content">
                                <h1 class="title-card center">
                                    ADICIONAR GANHO
                                </h1>
                                <div class="row">
                                    <form action=""  method="POST" class="add-exp-form">
                                        {% csrf_token %}
                                        <div class="row">
                                            <div class="input-field col s12 m6 l6">
                                                <i class="material-icons prefix update-icon">create</i>
                                                {{form.title}}
                                                <label for="title">Título</label>
                                                <span class="helper-text red-text" 
                                                data-error="wrong" data-success="right">
                                                    {{form.title.errors}}
                                                </span>
                                            </div>
                                            <div class="input-field col s12 m6 l6">
                                                <i class="material-icons prefix update-icon">
                                                    format_list_bulleted
                                                </i>
                                                <select id="id_earn_category" name="category">
                                                    {% for category in form.category %}
                                                    {{category}}
                                                    {% endfor %}
                                                </select>
                                                <label>Categoria</label>
                                                <span class="helper-text red-text" 
                                                data-error="wrong" data-success="right">
                                                    {{form.category.errors}}
                                                </span>
                                            </div>
                                        </div> 
                                        <div class="row">
                                            <div class="input-field col s12 m6 l6">
                                                <i class="material-icons prefix update-icon">
                                                    attach_money
                                                </i>
                                                {{form.quantity}}
                                                <label for="title">Valor</label>
                                                <span class="helper-text red-text" 
                                                data-error="wrong" data-success="right">
                                                    {{form.quantity.errors}}
                                                </span>
                                            </div>
                                            <div class="input-field col s12 m6 l6">
                                                <i class="material-icons prefix update-icon">
                                                    monetization_on
                                                </i>
                                                <select id="id_earns_currency" name="currency">
                                                    {% for c in form.currency %}
                                                    {{c}}
                                                    {% endfor %}
                                                </select>
                                                <label>Moeda</label>
                                                <span class="helper-text red-text" 
                                                data-error="wrong" data-success="right">
                                                    {{form.currency.errors}}
                                                </span>
                                            </div>
                                        </div> 
                                        <div class="row">
                                            <div class="input-field col s12 l12 m12">
                                                <i class="material-icons prefix update-icon">
                                                    description
                                                </i>
                                                {{form.description}}
                                                <label for="description">Descrição</label>
                                                <span class="helper-text red-text" 
                                                data-error="wrong" data-success="right">
                                                    {{form.description.errors}}
                                                </span>
                                            </div>
                                        </div> 
                                        <div class="row">
                                            <div class="input-field col s12 l12 m12">
                                                <i class="material-icons prefix 
                                                    update-icon">date_range
                                                </i>
                                                {{form.date}}
                                                <label for="date">Data</label>
                                                <span class="helper-text red-text" 
                                                data-error="wrong" data-success="right">
                                                    {{form.date.errors}}
                                                </span>
                                            </div>
                                        </div>  
                                        <label class="col s2 l3 m3 check-label">
                                            {{form.long_term}}
                                            <span class="text-card">
                                                Ganho Mensal
                                            </span>
                                        </label> 
                                        <span class="helper-text red-text" 
                                            data-error="wrong" data-success="right">
                                            {{form.long_term.errors}}
                                        </span>
                                        <button type="submit" class="btn btn-add">Adicionar</button>                    
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% include 'parciais/float_menu.html' %}
            </div>
        </section>                  
    </main>
{% endblock %}

earns/templates/earns/delete_earn.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Apagar | {{object.title}}{% endblock %}

{% block content %}
    <main class="main-delete-exp" style="background-image: url('{% static 'assets/img/delete_exp.jpg' %}')">
        <section>
            <div class="container card-container">
                <div class="row">
                    <div class="col s12 m10 l6 offset-m1 offset-l3">
                        <div class="card card-delete">
                            <div class="card-content">
                                    <h1 class="title-card center">
                                        Tem certeza que deseja excluir "{{object.title}}"?
                                    </h1>
                                    <div class="divider"></div>
                                    <form action="" method="POST">
                                        {% csrf_token %}
                                        <a href="{% url 'earn:list' %}" class="btn btn-cancel">
                                            Cancelar
                                        </a>
                                        <button type="submit" class="btn btn-delete 
                                        center">
                                            Excluir
                                        </button>                    
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% include 'parciais/float_menu.html' %}
            </div>
        </section>                  
    </main>
{% endblock %}
    

earns/templates/earns/earnings.html
{% extends 'base.html' %}
{% load static %}    

{% block title %}Meus Ganhos{% endblock %}

{% block content %}
    <main class="main-content">
        <section class="center">
            <div class="container card-container">
                <div class="row">
                    <div class="col s12 m10 l10 offset-l1 offset-m1">
                        <div class="card card-filter">
                            <div class="card-body">
                                <p class="text-card title-filter">
                                    <i class="material-icons">
                                        filter_list
                                    </i>
                                    Filtrar por
                                </p>
                                <div class="row">
                                    <div class="col l12 m12 s12">
                                        <form action="" method="GET" class="filter-form">
                                            <div class="input-field col s12 m6 l3">
                                                {{filter.form.category}}
                                                <label>Categoria</label>
                                            </div>  
                                            <div class="input-field col s12 m6 l3">
                                                {{filter.form.currency}}
                                                <label>Moeda</label>
                                            </div> 
                                            <div class="input-field col s12 m6 l3">
                                                {{filter.form.long_term}}
                                                <label>Mensal</label>
                                            </div>  
                                            <div class="input-field col s12 m6 l3">
                                                {{filter.form.start_date}}
                                                <label>Data (Intervalo inicial)</label>
                                            </div>
                                            <div class="input-field col s12 m6 l3">
                                                {{filter.form.end_date}}
                                                <label>Data (Intervalo final)</label>
                                            </div>
                                            <button type="submit" class="btn btn-filter">
                                                Filtrar
                                            </button>
                                        </form>
                                    </div>    
                                </div>
                            </div>        
                        </div>        
                    </div>
                </div>
            </div>
        </section>
        <section class="center">
            <div class="container">
                <div class="container search-container">
                    <h1 class="title center">Meus ganhos</h1>
                    <div class="row">
                        <div class="col l12 s10 m12">
                            <form action="{% url 'earn:search' %}" method="GET">
                                <div class="input-field search">
                                    <input class="white search-input" type="text" name="q" 
                                    value="{{request.GET.q}}"
                                    id="input-search">
                                    <label class="label-icon" for="search">
                                        <i class="material-icons right black-text">search</i>
                                    </label>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="row center">
                    {% include 'parciais/messages.html' %}
                    {% if earns %}
                    {% for earn in object_list %}
                    <div class="col l4 m6 s12">
                        <div class="card card-expense">
                            <div class="card-content">
                                <a href="{% url 'earn:delete' earn.pk %}">
                                    <i class="material-icons left">
                                        close
                                    </i>
                                </a>
                                <p class="title-card activator">
                                    {{earn.title | truncatechars:17 }}
                                    <i class="material-icons right">
                                        more_vert
                                    </i>
                                </p>
                                <p class="text-card">{{earn.currency}} {{earn.quantity}}</p>
                            </div>
                            <div class="card-reveal">
                                <span class="card-title title-card">
                                    <a href="{% url 'earn:update' earn.pk %}">
                                        <i class="material-icons left">
                                        mode_edit
                                    </i>
                                    </a>
                                    {{earn.category}}
                                    <i class="material-icons right">
                                        close
                                    </i>
                                </span>
                                <p class="text-card">
                                    {{earn.description}}
                                </p>
                            </div>
                            <div class="card-action">
                                {% if not earn.long_term %}
                                <p class="text-card">
                                    {{earn.date | date:"d/m/Y"}}
                                </p>
                                {% else %}
                                <p class="text-card">
                                    Dia {{earn.date | date:"d"}}
                                    <a href="#" class="tooltipped" 
                                        data-position="bottom" data-tooltip="Ganho mensal">
                                        <i class="material-icons green-text">
                                            date_range
                                        </i>
                                    </a>
                                </p>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% include 'parciais/pagination.html'%}
                {% endif %}
                {% include 'parciais/float_menu.html' %}
            </div>
        </section>    
    </main>
{% endblock %}
   